### ISSUE TITLE
Feature Request: Unfold All

### ISSUE THREAD

**Issue by ALameLlama** [chrisgrieser/nvim-origami#10]
### Feature Requested

If you've folded a bunch of stuff it can be a pain to unfold everything, It would be nice to have a command `:UnfoldAll` or function to unfold everything on the current buffer or current context.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
There is already a built-in vim command for that: https://neovim.io/doc/user/fold.html#zR
