### ISSUE TITLE
[Bug]: Error when closing neovim with only neogit buffer open

### ISSUE THREAD

**Issue by stelcodes** [chrisgrieser/nvim-origami#11]
### Bug Description

```
Error detected while processing BufWinLeave Autocommands for "?*":                                                                              
Error executing lua callback: .../nvim-origami/lua/origami/keep-folds-across-sessions.lua:27: Vim:E32: No file name                             
stack traceback:                                                                                                                                
        [C]: in function 'mkview'                                                                                                               
        .../nvim-origami/lua/origami/keep-folds-across-sessions.lua:27: in function 'remember'                                                  
        .../nvim-origami/lua/origami/keep-folds-across-sessions.lua:40: in function <.../nvim-origami/lua/origami/keep-folds-across-sessions.lua
:40>  
```

### To Reproduce

1. Open neovim
2. Open neogit: `:Neogit`
3. `:q`
4. Error occurs

### neovim version

```Text
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713773202
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
> 1. Open neovim
> 2. Open neogit: :Neogit
> 3. :wq

I cannot reproduce, `:wq` results in `E382: Cannot write, 'buftype' option is set` for me.

**Comment by chrisgrieser** [comment]
I added a small fix which might fix this regardless, though I am not totally sure if that one works of course.

**Comment by stelcodes** [comment]
@chrisgrieser I just tested with your minimal repro and the issue is gone, I think it might have something to do with an improper Neogit configuration causing Neogit to act funny. Thanks!
