### ISSUE TITLE
[Bug]: Pause folds while searching does not work with other plugin that maps N/n

### ISSUE THREAD

**Issue by pchampio** [chrisgrieser/nvim-origami#2]
### Bug Description

Pause folds while searching does not work with https://github.com/wincent/loupe since loupe rebinds n to an internal function. https://github.com/chrisgrieser/nvim-origami/blob/7bc3fd9e8cba3c3ccc64874b32568102eac7214e/lua/origami.lua#L95

### neovim version

```
TextNVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by pchampio** [comment]
Maybe fixable with autocmd:

```lua
vim.cmd[[
function! SearchMatch()
echomsg "Search" . strftime('%Y-%m-%d %H:%M:%S')
endfunction

autocmd CursorMoved * if getline('.')[col('.') - 1 : col('.') - 2] ==# matchstr(@/, '^\%'.line('.').'l\%<'.col('.').'c.\{-}\ze') | call SearchMatch() | endif
]]
```

**Comment by chrisgrieser** [comment]
The way this plugin works it is simply incompatible with other plugins that map n/N yes. Not sure whether it is fixable.

**Comment by pchampio** [comment]
Fixed by adding `":"` to `searchKeys`: `local searchKeys = { "n", "N", "*", "#", ":" } `

**Comment by chrisgrieser** [comment]
Closing, since not actionable on this plugin's end
