### ISSUE TITLE
[Bug]: Comments are not fold

### ISSUE THREAD

**Issue by kobzar** [chrisgrieser/nvim-origami#3]
### Bug Description

Commented line are not folded.

### To Reproduce

When i try to fold some of commented block folding doesn't work
Not for H key not for zf key
When i try to zf i've got error
"E350: Cannot create fold with current 'foldmethod'"

### neovim version

```Text
0.9.4
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
This plugin does not alter the `foldmethod` in any way, so you probably have an issue with some other plugin. Try disabling origami and then manually folding with `zc`, which I assume will also not work.

If I am wrong, and the issue goes away after disabling origami, please comment with more detailed reproduction steps (concrete code, other folding plugins you have installed, etc.) and I'll re-open
