### ISSUE TITLE
[Bug]: Undocumented side effects of keep_folds_across_sessions

### ISSUE THREAD

**Issue by jooooscha** [chrisgrieser/nvim-origami#4]
### Bug Description

This is not necessarily a bug but it cost me some time to figure out what was happening, because the following behavior is undocumented.

The `keep_folds_across_sessions ` option uses the `mkview` function to store the folds. However, by default, `mkview` includes the `curdir` (current directory) of the file. (this is defined using the `viewoptions` variable ([docs](https://neovim.io/doc/user/options.html#'viewoptions'))). This caused my Neovim to seemingly randomly change the directory when entering files that I opened from another directory before. I did not expect this behavior from an option called `keep_folds_across_sessions`.

Because of the above, I propose to document this behavior in the README by explaining that `mkview` is used to implement said option and that `mkview` saves the `lcd` by default and how to change that with a link to the NeoVim docs.

Thanks for considering my proposal, and thanks for creating this plugin :)

### neovim version

```Text
v0.9.4
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
good point. added to the docs
