### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by hrqmonteiro** [chrisgrieser/nvim-origami#5]
### Bug Description

I setup with lazy with the default options and setup, i press H and nothing works

### neovim version

```Text
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634
Compilation: /usr/bin/cc  -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-5_1-2.1 -I/usr/include -I/usr/include/lua5.1 -I/home/abuild/rpmbuild/BUILD/neovim-0.9.5/build/src/nvim/auto -I/home/abuild/rpmbuild/BUILD/neovim-0.9.5/build/include -I/home/abuild/rpmbuild/BUILD/neovim-0.9.5/build/cmake.config -I/home/abuild/rpmbuild/BUILD/neovim-0.9.5/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
```


### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
It's `h`, not `H`. 

If that was just a typo, you have to share a bit more specific information, like share example text you tried.

**Comment by hrqmonteiro** [comment]
> It's `h`, not `H`.
> 
> If that was just a typo, you have to share a bit more specific information, like share example text you tried. The "to reproduce" section is not decorative.

Was just a typo, i am pressing `h` indeed

I tried actually with my own nvim lua config, with some projects in react, some code in go, actually nothing folds

`h` just goes one character to the right, if i am not at the beginning of the line. If i am on the beginning of the line, it does nothing

**Comment by chrisgrieser** [comment]
Does normal folding via `zc` work?

**Comment by hrqmonteiro** [comment]
> Does normal folding via `zc` work?

```
E490: No fold found
```

I have

```
set foldenable
set foldmethod="manual"
```

on my configs

**Comment by hrqmonteiro** [comment]
Nevermind, just tried [nvim-ufo](https://github.com/kevinhwang91/nvim-ufo) and it works flawlessly out of the box.

Yours doesn't work. You should really see that.

**Comment by chrisgrieser** [comment]
> Yours doesn't work. 

I don't think you have understood what this plugin does, it is not an alternative but a complement to nvim-ufo. That zc is not working for you shows that you were missing a folding provider, which you got by installing nvim-ufo. 

> You should really see that.

I don't think that time is adequate, considering you haven't set up a folding provider. This plugin is working as intended. Please read the readme before creating spurious, low effort bug report next time.
