### ISSUE TITLE
[Bug]: L mapping doens't work with hardtime

### ISSUE THREAD

**Issue by superzanti** [chrisgrieser/nvim-origami#6]
### Bug Description

Fantastic plugin! Thank you for taking the time to develop this.

I noticed that when using (hardtime.nvim){https://github.com/m4xshen/hardtime.nvim} the "l" key doesn't open a fold.
Simply disabling this plugin fixed the issue, but I figured I should report it here for anyone else having trouble with it.

This may not be a bug in this plugin at all but simply an issue with conflicting keymappings.

### neovim version

```Text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068

Run ":verbose version" for more info
```
```


### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
Thanks!

Yes indeed, it's not really a bug, simply conflicting keymaps. It's not possible for two plugins to map the same key. 

So you get used to vim motions fast, so you can ditch hardtime and start using origami ;)
