### ISSUE TITLE
Feature Request: Allow map arrow keys

### ISSUE THREAD

**Issue by vunhatchuong** [chrisgrieser/nvim-origami#8]
### Feature Requested

I want to map arrow keys to fold/unfold as well since I'm using non QWERTY layout.

### Relevant Screenshot

I also tried to set a custom keymap like the example in `README` but it doesn't work.

```lua
return {
        "chrisgrieser/nvim-origami",
        event = "BufReadPost",
        opts = {
            setupFoldKeymaps = false,
        },
        config = function(_, opts)
            require("origami").setup(opts)
            require("origami").h()
            require("origami").l()
        end,
    },
```
`h` and `l` don't fold/unfold.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
That's not how keymaps in nvim work. Your config does nothing, because you have not assigned the functions to anything.

You need something like this:

```lua
vim.keymap.set("n", "<Left>", function require("origami").h() end)
vim.keymap.set("n", "<Right>", function require("origami").l() end)
```
